# services/word_generator.py
from pathlib import Path
from typing import Dict
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

from schemas.report import ReportPayload


class WordGenerator:
    def generate(
        self,
        report: ReportPayload,
        chart_paths: Dict[str, Path],
        output_path: Path,
    ) -> Path:
        doc = Document()

        # Configure Margins
        sections = doc.sections
        for section in sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.8)
            section.right_margin = Inches(0.8)

        # 1. Header Banner
        p_org = doc.add_paragraph()
        p_org_run = p_org.add_run("KARNATAKA STATE POLICE • INTELLIGENCE UNIT")
        p_org_run.font.size = Pt(9)
        p_org_run.font.bold = True
        p_org_run.font.color.rgb = RGBColor(15, 118, 110)

        p_title = doc.add_paragraph()
        p_title_run = p_title.add_run(report.title)
        p_title_run.font.size = Pt(20)
        p_title_run.font.bold = True
        p_title_run.font.color.rgb = RGBColor(15, 23, 42)

        # Meta table
        meta_table = doc.add_table(rows=1, cols=3)
        meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        meta_table.autofit = False

        cells = meta_table.rows[0].cells
        cells[0].text = f"Generated On:\n{report.generated_at}"
        cells[1].text = f"Generated By:\n{report.generated_by}"
        cells[2].text = "Classification:\nCONFIDENTIAL"

        for cell in cells:
            self._set_cell_background(cell, "F8FAFC")
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(8.5)
                    run.font.color.rgb = RGBColor(71, 85, 105)

        doc.add_paragraph()  # Spacer

        # 2. Executive Summary
        if report.executive_summary:
            self._add_heading(doc, "Executive Summary")
            summary_p = doc.add_paragraph(report.executive_summary)
            summary_p.style = "Quote"

        # 3. Visual Analytics
        if report.visualizations:
            self._add_heading(doc, "Visual Analytics")
            for viz in report.visualizations:
                if viz.id in chart_paths and chart_paths[viz.id].exists():
                    p_chart_title = doc.add_paragraph()
                    r = p_chart_title.add_run(viz.title)
                    r.font.bold = True
                    r.font.size = Pt(11)

                    doc.add_picture(str(chart_paths[viz.id]), width=Inches(6.0))

                    if viz.reason:
                        p_reason = doc.add_paragraph()
                        r_reason = p_reason.add_run(viz.reason)
                        r_reason.font.italic = True
                        r_reason.font.size = Pt(9)
                        r_reason.font.color.rgb = RGBColor(100, 116, 139)

                    doc.add_paragraph()  # Spacer

        # 4. SQL Query
        self._add_heading(doc, "Executed Query")
        sql_p = doc.add_paragraph()
        sql_run = sql_p.add_run(report.sql.query)
        sql_run.font.name = "Courier New"
        sql_run.font.size = Pt(8.5)

        # 5. SQL Results Table
        if report.sql.rows:
            self._add_heading(doc, f"Query Result Set ({report.sql.row_count} records)")

            columns = list(report.sql.rows[0].keys())
            table = doc.add_table(rows=1, cols=len(columns))
            table.alignment = WD_TABLE_ALIGNMENT.CENTER

            # Header Row
            hdr_cells = table.rows[0].cells
            for idx, col_name in enumerate(columns):
                hdr_cells[idx].text = str(col_name)
                self._set_cell_background(hdr_cells[idx], "F1F5F9")
                hdr_cells[idx].paragraphs[0].runs[0].font.bold = True
                hdr_cells[idx].paragraphs[0].runs[0].font.size = Pt(8.5)

            # Data Rows
            for row in report.sql.rows:
                row_cells = table.add_row().cells
                for idx, col_name in enumerate(columns):
                    val = row.get(col_name)
                    row_cells[idx].text = "—" if val is None else str(val)
                    if len(row_cells[idx].paragraphs[0].runs) > 0:
                        row_cells[idx].paragraphs[0].runs[0].font.size = Pt(8.5)

        # Save Document
        doc.save(str(output_path))
        return output_path

    def _add_heading(self, doc: Document, text: str):
        h = doc.add_paragraph()
        run = h.add_run(text)
        run.font.size = Pt(12)
        run.font.bold = True
        run.font.color.rgb = RGBColor(15, 23, 42)
        h.paragraph_format.space_before = Pt(12)
        h.paragraph_format.space_after = Pt(4)

    def _set_cell_background(self, cell, hex_color: str):
        shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>')
        cell._tc.get_or_add_tcPr().append(shading)