# services/word_generator.py
import re
from pathlib import Path
from typing import Dict
from docx import Document
from docx.shared import Inches, Pt, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

from schemas.report import ReportPayload

# ── Design Tokens (matches frontend UI) ──────────────────────────────────────
TEAL       = RGBColor(15, 118, 110)   # #0f766e
SLATE_900  = RGBColor(15, 23, 42)     # #0f172a
SLATE_700  = RGBColor(51, 65, 85)     # #334155
SLATE_600  = RGBColor(71, 85, 105)    # #475569
SLATE_500  = RGBColor(100, 116, 139)  # #64748b
SLATE_400  = RGBColor(148, 163, 184)  # #94a3b8
WHITE      = RGBColor(255, 255, 255)
BG_SLATE_50  = "F8FAFC"
BG_SLATE_100 = "F1F5F9"
BG_SLATE_950 = "0F172A"
BORDER_SLATE_200 = "E2E8F0"


class WordGenerator:
    def generate(
        self,
        report: ReportPayload,
        chart_paths: Dict[str, Path],
        output_path: Path,
    ) -> Path:
        doc = Document()

        # ── Page Setup ────────────────────────────────────────────────────
        for section in doc.sections:
            section.top_margin = Inches(0.9)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.9)
            section.right_margin = Inches(0.9)

        style = doc.styles["Normal"]
        style.font.name = "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif"
        style.font.size = Pt(10)
        style.font.color.rgb = SLATE_700
        style.paragraph_format.space_after = Pt(4)
        style.paragraph_format.line_spacing = 1.45

        # ── Teal Accent Bar ───────────────────────────────────────────────
        bar_p = doc.add_paragraph()
        bar_p.paragraph_format.space_before = Pt(0)
        bar_p.paragraph_format.space_after = Pt(10)
        bar_run = bar_p.add_run()
        bar_run.font.size = Pt(2)
        # Top border as accent (thin teal line)
        pPr = bar_p._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), "24")
        bottom.set(qn("w:space"), "0")
        bottom.set(qn("w:color"), "0F766E")
        pBdr.append(bottom)
        pPr.append(pBdr)

        # ── Organization Title ────────────────────────────────────────────
        p_org = doc.add_paragraph()
        p_org.paragraph_format.space_after = Pt(2)
        r_org = p_org.add_run("KARNATAKA STATE POLICE • INTELLIGENCE UNIT")
        r_org.font.size = Pt(8.5)
        r_org.font.bold = True
        r_org.font.color.rgb = TEAL
        r_org.font.letter_spacing = Pt(0.5)

        # ── Report Title ──────────────────────────────────────────────────
        p_title = doc.add_paragraph()
        p_title.paragraph_format.space_after = Pt(2)
        r_title = p_title.add_run(report.title)
        r_title.font.size = Pt(22)
        r_title.font.bold = True
        r_title.font.color.rgb = SLATE_900

        # ── Subtitle ──────────────────────────────────────────────────────
        p_sub = doc.add_paragraph()
        p_sub.paragraph_format.space_after = Pt(10)
        r_sub = p_sub.add_run("Investigative Analysis Report")
        r_sub.font.size = Pt(9)
        r_sub.font.color.rgb = SLATE_500

        # ── Metadata Bar ──────────────────────────────────────────────────
        meta_table = doc.add_table(rows=1, cols=3)
        meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        meta_table.autofit = True

        meta_entries = [
            ("Generated On", report.generated_at),
            ("Generated By", report.generated_by),
            ("Classification", "CONFIDENTIAL"),
        ]
        for idx, (label, value) in enumerate(meta_entries):
            cell = meta_table.rows[0].cells[idx]
            # Clear default empty paragraph
            cell.paragraphs[0].clear()
            # Label
            p_label = cell.paragraphs[0]
            r_label = p_label.add_run(label.upper())
            r_label.font.size = Pt(7)
            r_label.font.bold = True
            r_label.font.color.rgb = SLATE_400
            # Value
            p_val = cell.add_paragraph()
            r_val = p_val.add_run(value)
            r_val.font.size = Pt(8.5)
            if label == "Classification":
                r_val.font.color.rgb = RGBColor(220, 38, 38)
                r_val.font.bold = True
            else:
                r_val.font.color.rgb = SLATE_600
            # Cell bg
            self._set_cell_background(cell, BG_SLATE_50)
            # Cell border
            self._set_cell_border(cell, color=BORDER_SLATE_200)

        doc.add_paragraph()  # spacer

        # ── Agent Analysis Response (rich markdown) ───────────────────────
        if report.analysis_response:
            self._add_section_heading(doc, "Agent Analysis")
            self._render_markdown(doc, report.analysis_response)
        elif report.executive_summary:
            self._add_section_heading(doc, "Executive Summary")
            p_sum = doc.add_paragraph()
            p_sum.paragraph_format.left_indent = Inches(0.2)
            # Left border via XML
            pPr = p_sum._p.get_or_add_pPr()
            pBdr = OxmlElement("w:pBdr")
            left_bdr = OxmlElement("w:left")
            left_bdr.set(qn("w:val"), "single")
            left_bdr.set(qn("w:sz"), "12")
            left_bdr.set(qn("w:space"), "8")
            left_bdr.set(qn("w:color"), "0F766E")
            pBdr.append(left_bdr)
            pPr.append(pBdr)
            # Background shading
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear")
            shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), BG_SLATE_50)
            pPr.append(shd)

            r_sum = p_sum.add_run(report.executive_summary)
            r_sum.font.size = Pt(9.5)
            r_sum.font.color.rgb = SLATE_700

        # ── Visual Analytics ──────────────────────────────────────────────
        if report.visualizations:
            self._add_section_heading(doc, "Visual Analytics")
            for viz in report.visualizations:
                if viz.id in chart_paths and chart_paths[viz.id].exists():
                    # Chart title with teal dot
                    p_ct = doc.add_paragraph()
                    p_ct.paragraph_format.space_before = Pt(8)
                    p_ct.paragraph_format.space_after = Pt(4)
                    # Teal bullet
                    r_dot = p_ct.add_run("●  ")
                    r_dot.font.size = Pt(8)
                    r_dot.font.color.rgb = TEAL
                    # Title text
                    r_ct = p_ct.add_run(viz.title)
                    r_ct.font.bold = True
                    r_ct.font.size = Pt(11)
                    r_ct.font.color.rgb = SLATE_900

                    # Chart image
                    pic = doc.add_picture(
                        str(chart_paths[viz.id]), width=Inches(6.0)
                    )
                    last_paragraph = doc.paragraphs[-1]
                    last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

                    # Reason / caption
                    if viz.reason:
                        p_reason = doc.add_paragraph()
                        p_reason.paragraph_format.space_before = Pt(4)
                        p_reason.paragraph_format.space_after = Pt(10)
                        r_reason = p_reason.add_run(viz.reason)
                        r_reason.font.italic = True
                        r_reason.font.size = Pt(8.5)
                        r_reason.font.color.rgb = SLATE_500

        # ── Executed Query ────────────────────────────────────────────────
        self._add_section_heading(doc, "Executed Query")
        # Dark code block
        sql_p = doc.add_paragraph()
        sql_p.paragraph_format.space_before = Pt(4)
        sql_p.paragraph_format.space_after = Pt(6)
        # Background
        pPr = sql_p._p.get_or_add_pPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"), BG_SLATE_950)
        pPr.append(shd)
        # Border
        pBdr = OxmlElement("w:pBdr")
        for edge in ("top", "bottom", "left", "right"):
            e = OxmlElement(f"w:{edge}")
            e.set(qn("w:val"), "single")
            e.set(qn("w:sz"), "4")
            e.set(qn("w:space"), "0")
            e.set(qn("w:color"), "1E293B")
            pBdr.append(e)
        pPr.append(pBdr)
        # Indent
        pPr.append(OxmlElement("w:ind"))
        pPr[-1].set(qn("w:left"), "120")
        pPr[-1].set(qn("w:right"), "120")

        sql_run = sql_p.add_run(report.sql.query)
        sql_run.font.name = "Courier New"
        sql_run.font.size = Pt(8)
        sql_run.font.color.rgb = RGBColor(226, 232, 240)  # slate-200

        # ── SQL Results Table ─────────────────────────────────────────────
        if report.sql.rows:
            self._add_section_heading(
                doc, f"Query Result Set ({report.sql.row_count} records)"
            )

            columns = list(report.sql.rows[0].keys())
            table = doc.add_table(rows=1, cols=len(columns))
            table.alignment = WD_TABLE_ALIGNMENT.CENTER
            table.autofit = True

            # Set table width to full page
            tbl = table._tbl
            tblPr = tbl.tblPr if tbl.tblPr is not None else OxmlElement("w:tblPr")
            tblW = OxmlElement("w:tblW")
            tblW.set(qn("w:type"), "pct")
            tblW.set(qn("w:w"), "5000")
            tblPr.append(tblW)

            # Header row
            hdr_cells = table.rows[0].cells
            for idx, col_name in enumerate(columns):
                cell = hdr_cells[idx]
                cell.paragraphs[0].clear()
                r = cell.paragraphs[0].add_run(str(col_name))
                r.font.bold = True
                r.font.size = Pt(7.5)
                r.font.color.rgb = SLATE_700
                self._set_cell_background(cell, BG_SLATE_100)

            # Data rows
            for row_idx, row in enumerate(report.sql.rows):
                row_cells = table.add_row().cells
                for idx, col_name in enumerate(columns):
                    val = row.get(col_name)
                    cell = row_cells[idx]
                    cell.paragraphs[0].clear()
                    r = cell.paragraphs[0].add_run(
                        "—" if val is None else str(val)
                    )
                    r.font.size = Pt(8)
                    r.font.color.rgb = SLATE_700
                    if row_idx % 2 == 1:
                        self._set_cell_background(cell, BG_SLATE_50)

            # Apply borders to all cells
            for row in table.rows:
                for cell in row.cells:
                    self._set_cell_border(cell, color=BORDER_SLATE_200)

        # ── Recommended Follow-ups ────────────────────────────────────────
        if report.follow_up_questions:
            self._add_section_heading(doc, "Recommended Follow-Up Actions")
            for q in report.follow_up_questions:
                p_fu = doc.add_paragraph()
                p_fu.paragraph_format.space_before = Pt(2)
                p_fu.paragraph_format.space_after = Pt(2)
                p_fu.paragraph_format.left_indent = Inches(0.15)
                # Arrow prefix
                r_arrow = p_fu.add_run("→  ")
                r_arrow.font.color.rgb = TEAL
                r_arrow.font.bold = True
                r_arrow.font.size = Pt(9.5)
                # Question text
                r_q = p_fu.add_run(q)
                r_q.font.size = Pt(9.5)
                r_q.font.color.rgb = SLATE_700

        # ── Save ──────────────────────────────────────────────────────────
        doc.save(str(output_path))
        return output_path

    # ── Markdown Renderer ────────────────────────────────────────────────────

    def _render_markdown(self, doc: Document, text: str):
        """Parse markdown text and render as rich Word paragraphs."""
        if not text or not text.strip():
            return

        lines = text.split("\n")
        i = 0

        while i < len(lines):
            line = lines[i]
            stripped = line.strip()

            # Blank line -> small paragraph break
            if not stripped:
                i += 1
                continue

            # Heading
            heading_match = re.match(r"^(#{1,6})\s+(.+)$", stripped)
            if heading_match:
                level = len(heading_match.group(1))
                content = heading_match.group(2)
                p = doc.add_paragraph()
                size = {1: 13, 2: 11.5, 3: 10.5, 4: 10, 5: 9.5, 6: 9}
                p.paragraph_format.space_before = Pt(10 if level <= 2 else 6)
                p.paragraph_format.space_after = Pt(3)
                run = p.add_run(content)
                run.font.bold = True
                run.font.size = Pt(size.get(level, 10))
                run.font.color.rgb = SLATE_900 if level <= 2 else TEAL
                # Border under h1/h2
                if level <= 2:
                    pPr = p._p.get_or_add_pPr()
                    pBdr = OxmlElement("w:pBdr")
                    bottom = OxmlElement("w:bottom")
                    bottom.set(qn("w:val"), "single")
                    bottom.set(qn("w:sz"), "4" if level == 1 else "2")
                    bottom.set(qn("w:space"), "2")
                    bottom.set(qn("w:color"), BORDER_SLATE_200)
                    pBdr.append(bottom)
                    pPr.append(pBdr)
                i += 1
                continue

            # Unordered list
            if re.match(r"^[-*+]\s+", stripped):
                while i < len(lines) and re.match(
                    r"^[-*+]\s+", lines[i].strip()
                ):
                    item_text = re.sub(
                        r"^[-*+]\s+", "", lines[i].strip()
                    )
                    p = doc.add_paragraph()
                    p.paragraph_format.left_indent = Inches(0.25)
                    p.paragraph_format.first_line_indent = Inches(-0.15)
                    p.paragraph_format.space_before = Pt(1)
                    p.paragraph_format.space_after = Pt(1)
                    r_bullet = p.add_run("•  ")
                    r_bullet.font.color.rgb = TEAL
                    r_bullet.font.size = Pt(9)
                    self._add_inline_runs(p, item_text)
                    i += 1
                continue

            # Ordered list
            if re.match(r"^\d+\.\s+", stripped):
                counter = 1
                while i < len(lines) and re.match(
                    r"^\d+\.\s+", lines[i].strip()
                ):
                    item_text = re.sub(
                        r"^\d+\.\s+", "", lines[i].strip()
                    )
                    p = doc.add_paragraph()
                    p.paragraph_format.left_indent = Inches(0.25)
                    p.paragraph_format.first_line_indent = Inches(-0.15)
                    p.paragraph_format.space_before = Pt(1)
                    p.paragraph_format.space_after = Pt(1)
                    r_num = p.add_run(f"{counter}.  ")
                    r_num.font.bold = True
                    r_num.font.color.rgb = TEAL
                    r_num.font.size = Pt(9)
                    self._add_inline_runs(p, item_text)
                    counter += 1
                    i += 1
                continue

            # Blockquote
            if stripped.startswith(">"):
                p = doc.add_paragraph()
                p.paragraph_format.left_indent = Inches(0.25)
                p.paragraph_format.space_before = Pt(4)
                p.paragraph_format.space_after = Pt(4)
                # Left border
                pPr = p._p.get_or_add_pPr()
                pBdr = OxmlElement("w:pBdr")
                left_bdr = OxmlElement("w:left")
                left_bdr.set(qn("w:val"), "single")
                left_bdr.set(qn("w:sz"), "12")
                left_bdr.set(qn("w:space"), "6")
                left_bdr.set(qn("w:color"), "CBD5E1")
                pBdr.append(left_bdr)
                pPr.append(pBdr)
                # Background
                shd = OxmlElement("w:shd")
                shd.set(qn("w:val"), "clear")
                shd.set(qn("w:color"), "auto")
                shd.set(qn("w:fill"), BG_SLATE_50)
                pPr.append(shd)

                quote_text = re.sub(r"^>\s?", "", stripped)
                r = p.add_run(quote_text)
                r.font.italic = True
                r.font.size = Pt(9)
                r.font.color.rgb = SLATE_500
                i += 1
                continue

            # Horizontal rule
            if re.match(r"^(-{3,}|\*{3,}|_{3,})$", stripped):
                p = doc.add_paragraph()
                p.paragraph_format.space_before = Pt(4)
                p.paragraph_format.space_after = Pt(4)
                pPr = p._p.get_or_add_pPr()
                pBdr = OxmlElement("w:pBdr")
                bottom = OxmlElement("w:bottom")
                bottom.set(qn("w:val"), "single")
                bottom.set(qn("w:sz"), "4")
                bottom.set(qn("w:space"), "2")
                bottom.set(qn("w:color"), BORDER_SLATE_200)
                pBdr.append(bottom)
                pPr.append(pBdr)
                i += 1
                continue

            # Paragraph
            para_lines = []
            while i < len(lines):
                s = lines[i].strip()
                if (
                    not s
                    or s.startswith("#")
                    or s.startswith(">")
                    or re.match(r"^[-*+]\s+", s)
                    or re.match(r"^\d+\.\s+", s)
                    or re.match(r"^(-{3,}|\*{3,}|_{3,})$", s)
                ):
                    break
                para_lines.append(s)
                i += 1
            if para_lines:
                p = doc.add_paragraph()
                p.paragraph_format.space_before = Pt(3)
                p.paragraph_format.space_after = Pt(3)
                self._add_inline_runs(p, " ".join(para_lines))

    def _add_inline_runs(self, paragraph, text: str):
        """Add inline markdown formatting (bold, italic, code) as runs."""
        # Split on patterns: **bold**, *italic*, `code`
        pattern = r"(\*\*(.+?)\*\*|\*(.+?)\*|`([^`]+)`)"
        last_end = 0

        for m in re.finditer(pattern, text):
            # Add plain text before this match
            if m.start() > last_end:
                plain = text[last_end : m.start()]
                r = paragraph.add_run(plain)
                r.font.size = Pt(9.5)
                r.font.color.rgb = SLATE_700

            if m.group(2):  # bold
                r = paragraph.add_run(m.group(2))
                r.font.bold = True
                r.font.size = Pt(9.5)
                r.font.color.rgb = SLATE_900
            elif m.group(3):  # italic
                r = paragraph.add_run(m.group(3))
                r.font.italic = True
                r.font.size = Pt(9.5)
                r.font.color.rgb = SLATE_600
            elif m.group(4):  # code
                r = paragraph.add_run(m.group(4))
                r.font.name = "Courier New"
                r.font.size = Pt(8.5)
                r.font.color.rgb = TEAL

            last_end = m.end()

        # Remaining plain text
        if last_end < len(text):
            r = paragraph.add_run(text[last_end:])
            r.font.size = Pt(9.5)
            r.font.color.rgb = SLATE_700

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _add_section_heading(self, doc: Document, text: str):
        h = doc.add_paragraph()
        h.paragraph_format.space_before = Pt(14)
        h.paragraph_format.space_after = Pt(6)

        # Left teal border
        pPr = h._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        left_bdr = OxmlElement("w:left")
        left_bdr.set(qn("w:val"), "single")
        left_bdr.set(qn("w:sz"), "18")
        left_bdr.set(qn("w:space"), "6")
        left_bdr.set(qn("w:color"), "0F766E")
        pBdr.append(left_bdr)
        pPr.append(pBdr)

        run = h.add_run(text.upper())
        run.font.size = Pt(10)
        run.font.bold = True
        run.font.color.rgb = SLATE_900
        run.font.letter_spacing = Pt(0.5)

    def _set_cell_background(self, cell, hex_color: str):
        shading = parse_xml(
            f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>'
        )
        cell._tc.get_or_add_tcPr().append(shading)

    def _set_cell_border(self, cell, color: str = "E2E8F0"):
        tc = cell._tc
        tcPr = tc.get_or_add_tcPr()
        borders = OxmlElement("w:tcBorders")
        for edge in ("top", "left", "bottom", "right"):
            e = OxmlElement(f"w:{edge}")
            e.set(qn("w:val"), "single")
            e.set(qn("w:sz"), "4")
            e.set(qn("w:space"), "0")
            e.set(qn("w:color"), color)
            borders.append(e)
        tcPr.append(borders)
